# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - serhii-func

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build Solution'
        shell: bash
        run: |
          pwd
          ls -la
          
          dotnet build "Function Integrated with Blob/Function.sln" --configuration Release --output "./buildOutput"

      - name: 'Publish for Azure Functions'
        shell: bash
        run: |
          dotnet publish "Function Integrated with Blob/Function.sln" --configuration Release --no-build --output "./buildOutput"

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'serhii-func'
          slot-name: 'Production'
          package: './buildOutput'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E17B06FF452B4DCF82EB22C83985BA55 }}
          sku: 'flexconsumption'
